import {
    Box,
    Text,
    VStack,
} from "@chakra-ui/react";

import { Outlet, Link, useLocation } from "react-router-dom";

export default function Brush() {
    return (
        <Box className="brush">    
            <div className='brush-title'>
                <Text
                  bgGradient='linear(to-r, #619BEB, #FFFFFF)'
                  bgClip='text'
                  // fontSize='6xl'
                  fontWeight='extrabold'
                >
                  What is MagicBrush?
                </Text>
            </div>
            <div className='brush-content'>
                Any manual sketch, drawing can be directly generated by MagicBrush creative images and 3D models.
                <br />
                3D model can be 3D printed directly
            </div>
            <div className='brush-more'><Link to="magicbrush">more</Link></div>
            <div className="brush-transfer">
                <table width="100%" border={0} cellSpacing={0} cellPadding={0}>
                    <tbody>
                        <tr>
                            <td width={"34%"}>Picture/Hand-drawn</td>
                            <td width={"35%"}>3D Rendering</td>
                            <td width={"31%"}>3D Modeling</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </Box>
    );
  }