import {
    Box,
    Text,
    VStack,
} from "@chakra-ui/react";

import "./magicbrush.css";


export default function MagicBrush() {
    return (
        <Box className="magicbrush">    
            <div className="magicbrush-inner">
                <div className='brush-title'>
                    <Text
                        bgGradient='linear(to-r, #619BEB, #FFFFFF)'
                        bgClip='text'
                        // fontSize='6xl'
                        fontWeight='extrabold'
                    >
                        What is MagicBrush?
                    </Text>
                </div>
                <div className='brush-content'>
                    Any manual sketch, drawing can be directly generated by MagicBrush creative images and 3D models.
                    <br />
                    3D model can be 3D printed directly
                </div>
                
                <div className="brush-transfer">
                    <table width="100%" border={0} cellSpacing={0} cellPadding={0}>
                        <tbody>
                            <tr>
                                <td width={"174"}>&nbsp;&nbsp;Picture/Hand-drawn</td>
                                <td width={"174"}>3D Rendering</td>
                                <td width={"174"}>3D Modeling&nbsp;&nbsp;&nbsp;&nbsp;</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div className='brush-more'><a href="">Try it, for free</a></div>
            </div>
        </Box>
    );
}